language: node_js
node_js:
 - "10.6.0"
 
before_install:
 - npm i -g npm@6.1.0

before_deploy:
 - npm run eslint
 - npm run tslint
 - npm run produce

deploy:
 skip_cleanup: true
 provider: surge
 project: ./build/
 domain: peterh-todolist.surge.sh
 on:
   branch: feature/task-5
